# Generated by Django 5.0 on 2024-03-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='area',
            field=models.CharField(choices=[('faxineira', 'Faxineira'), ('pintor', 'Pintor')], max_length=100),
        ),
    ]
